### ISSUE TITLE
.visually-hidden vs. .a11y

### ISSUE THREAD

**Issue by DracoBlue** [nikita-kit/nikita-css#6]
Hi @rastersysteme @lhtdesignde,

I set up a small codepen http://codepen.io/DracoBlue/pen/WroKeq to try the different versions of visually hiding things to keep them visible to screenreaders.

.visually-hidden (as proposed by @lhtdesignde):

``` css
.visually-hidden {
  overflow: hidden;
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  border: 0;
  padding: 0;
  clip: rect(0 0 0 0);
}
```

<img width="1440" alt="bildschirmfoto 2015-12-30 um 12 59 11" src="https://cloud.githubusercontent.com/assets/35926/12050429/b274add6-aef5-11e5-8b0c-c7071e102fb4.png">

.a11y (as refactored yesterday by @rastersysteme )

``` css
.a11y {
    clip: rect(1px, 1px, 1px, 1px);
    overflow: hidden;
    position: absolute;
    width: 1px;
    height: 1px;
}
```

<img width="1440" alt="bildschirmfoto 2015-12-30 um 12 59 23" src="https://cloud.githubusercontent.com/assets/35926/12050439/cd8fc830-aef5-11e5-8db3-1f5da338b0e0.png">

and .yahoo-visually-hidden (as proposed by a11yproject.com)

``` css
.yahoo-visually-hidden {
    position: absolute !important;
    clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px);
    padding:0 !important;
    border:0 !important;
    height: 1px !important;
    width: 1px !important;
    overflow: hidden;
}
```

<img width="1440" alt="bildschirmfoto 2015-12-30 um 13 01 30" src="https://cloud.githubusercontent.com/assets/35926/12050440/e1e8edb6-aef5-11e5-8aba-3c8db0a0db0e.png">

What do you think? Maybe we should go for the a11project.com version?

PS: I prefer the name .visually-hidden vs. a11y (because there are maybe other a11y-classes and not only the use case of actually making things visible only to the screen reader).
PPS: I asked at https://www.reddit.com/r/webdev/comments/3ys9bj/what_is_the_best_way_to_hide_things_except_for/ for more comments ;)
